// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P04Sklep.API.Data;

#nullable disable

namespace P04Sklep.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230131092533_seedProducts")]
    partial class seedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P05Sklep.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Color = "black",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Title = "Generic Wooden Tuna"
                        },
                        new
                        {
                            Id = 12,
                            Color = "ivory",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Title = "Refined Rubber Ball"
                        },
                        new
                        {
                            Id = 13,
                            Color = "teal",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Title = "Unbranded Soft Chair"
                        },
                        new
                        {
                            Id = 14,
                            Color = "lavender",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Title = "Gorgeous Fresh Chair"
                        },
                        new
                        {
                            Id = 15,
                            Color = "gold",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Title = "Refined Frozen Towels"
                        },
                        new
                        {
                            Id = 16,
                            Color = "sky blue",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Title = "Tasty Cotton Bike"
                        },
                        new
                        {
                            Id = 17,
                            Color = "lavender",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Title = "Unbranded Frozen Tuna"
                        },
                        new
                        {
                            Id = 18,
                            Color = "lavender",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Title = "Generic Fresh Chair"
                        },
                        new
                        {
                            Id = 19,
                            Color = "orchid",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Title = "Fantastic Soft Soap"
                        },
                        new
                        {
                            Id = 20,
                            Color = "pink",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Title = "Unbranded Frozen Mouse"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
