// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P04Sklep.API.Data;

#nullable disable

namespace P04Sklep.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P05Sklep.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 22,
                            Color = "mint green",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImgUrl = "https://loremflickr.com/320/240?lock=1203187029",
                            Title = "Sleek Wooden Salad"
                        },
                        new
                        {
                            Id = 23,
                            Color = "black",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUrl = "https://loremflickr.com/320/240?lock=1366534663",
                            Title = "Ergonomic Cotton Computer"
                        },
                        new
                        {
                            Id = 24,
                            Color = "mint green",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUrl = "https://loremflickr.com/320/240?lock=1238170192",
                            Title = "Refined Metal Table"
                        },
                        new
                        {
                            Id = 25,
                            Color = "pink",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUrl = "https://loremflickr.com/320/240?lock=1361857188",
                            Title = "Small Fresh Bike"
                        },
                        new
                        {
                            Id = 26,
                            Color = "fuchsia",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImgUrl = "https://loremflickr.com/320/240?lock=565333327",
                            Title = "Awesome Wooden Chair"
                        },
                        new
                        {
                            Id = 27,
                            Color = "turquoise",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImgUrl = "https://loremflickr.com/320/240?lock=1960881291",
                            Title = "Gorgeous Steel Computer"
                        },
                        new
                        {
                            Id = 28,
                            Color = "tan",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImgUrl = "https://loremflickr.com/320/240?lock=1222508578",
                            Title = "Refined Frozen Ball"
                        },
                        new
                        {
                            Id = 29,
                            Color = "pink",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImgUrl = "https://loremflickr.com/320/240?lock=1228279556",
                            Title = "Unbranded Frozen Shoes"
                        },
                        new
                        {
                            Id = 30,
                            Color = "gold",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImgUrl = "https://loremflickr.com/320/240?lock=1072843261",
                            Title = "Handmade Rubber Chair"
                        },
                        new
                        {
                            Id = 31,
                            Color = "gold",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImgUrl = "https://loremflickr.com/320/240?lock=213620396",
                            Title = "Tasty Concrete Sausages"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
